server:
    host: ${SERVER_HOST}
    port: ${SERVER_PORT}

database:
    name: ${DB_NAME}
    host: ${DB_HOST}
    port: ${DB_PORT}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    parseTime: ${DB_PARSE_TIME}
    charset: ${DB_CHARSET}

metrics:
    host: ${REPORTING_HOST}
    port: ${REPORTING_PORT}
    prefix: tutor
    maxFlushInterval: ${REPORTING_MAX_FLUSH_INTERVAL}
    maxFlushBytes: ${REPORTING_MAX_FLUSH_BYTES}
