{
 "title": "Unit Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Unit Save Success",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "stats.tutor.unit.save.success" }
   ]
  },
  {
   "title": "Unit Save Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.tutor.unit.save.mean, 'mean')"
    },
    {
     "target": "alias(stats.timers.tutor.unit.save.median, 'median')"
    },
    {
     "target": "alias(stats.timers.tutor.unit.save.upper, 'upper')"
    },
    {
     "target": "alias(stats.timers.tutor.unit.save.lower, 'lower')"
    }
   ]
  },
  {
   "title": "Unit Rollback Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.tutor.unit.rollback.success"
    }
   ]
  },
  {
   "title": "Unit Rollback Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.tutor.unit.rollback.mean, 'mean')"
    },
    {
     "target": "alias(stats.timers.tutor.unit.rollback.median, 'median')"
    },
    {
     "target": "alias(stats.timers.tutor.unit.rollback.upper, 'upper')"
    },
    {
     "target": "alias(stats.timers.tutor.unit.rollback.lower, 'lower')"
    }
   ]
  }
 ]
}